### ISSUE TITLE
License for mach_override and mach_install projects

### ISSUE THREAD

**Issue by rcontractor** [rentzsch/mach_override#9]
Hi. I am using the mach_install and mach_override projects in my code. It is imperative that I use this code, but unfortunately I cannot if there is not an explicit license. Can you please provide a license as soon as possible for each of the projects that grants permission to use them? I would really appreciate it as I have worked for a long time getting my project working with your code.
Thanks again!

**Comment by rentzsch** [comment]
The license is MIT, as indicated in the source file headers by the words "Some rights reserved".
